name: Gather Repository Stats and Test Workflow

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  gather_stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Gather Repository Stats
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: node gather_stats.js
