name: Gather Repository Stats
on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  gather_stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Gather Repository Stats
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: node gather_stats.js
